FROM openjdk:8-jre-alpine

ENV SCALA_VERSION 2.11.12
ENV SBT_VERSION 1.2.6

RUN apk add bash && \
    apk add --update --no-cache -t deps curl && \
    cd /tmp && \
    curl -fsSOL https://piccolo.link/sbt-$SBT_VERSION.tgz && \
    tar -xvzf sbt-$SBT_VERSION.tgz && \
    mv /tmp/sbt /usr/lib && \
    rm /tmp/sbt-$SBT_VERSION.tgz && \
    ln -s /usr/lib/sbt/bin/* /usr/local/bin && \
    apk del --purge deps && \
    sbt sbtVersion

WORKDIR /root
